export const tasks = [
    {
        id: "ygfy4r5cu1",
        name: "Eat",
        description: "Everyone",
        date: "2026-05-07T14:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiuii5cu1",
        name: "Drink",
        description: "Everyone",
        date: "2026-05-22T14:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5cu1",
        name: "Walk the dog",
        description: "Everyone",
        date: "2026-05-31T15:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5de2",
        name: "Walk the dog",
        description: "Everyone",
        date: "2026-06-30T15:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5cu3",
        name: "Walk the dog",
        description: "Everyone",
        date: "2026-06-21T15:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5cu4",
        name: "Walk the dog",
        description: "Everyone",
        date: "2026-07-21T15:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5c4",
        name: "Walk the dog",
        description: "Everyone",
        date: "2026-07-21T15:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5c5",
        name: "Walk the dog",
        description: "Everyone",
        date: "2026-07-21T15:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5c6",
        name: "Walk the dog",
        description: "Everyone",
        date: "2026-07-26T15:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5cu5",
        name: "Walk the dog",
        description: "Everyone",
        date: "2026-07-26T15:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5cu6",
        name: "Eat",
        description: "Everyone",
        date: "2026-07-26T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55ii5вcu7",
        name: "Drink",
        description: "Everyone",
        date: "2026-07-25T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiр55ii5u7",
        name: "Drink",
        description: "Everyone",
        date: "2026-07-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55пii5cu7",
        name: "Drink",
        description: "Everyone",
        date: "2026-07-28T16:00:00",
        completed: false,
        visibility: "public",
    },
    {
        id: "yiр55ii5u17",
        name: "Drink",
        description: "Everyone",
        date: "2026-08-21T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55пii5cu27",
        name: "Забрать ребенка",
        description: "Everyone",
        date: "2026-08-13T16:00:00",
        completed: false,
        visibility: "public",
    },
    {
        id: "yiр55ii5u37",
        name: "Сходить в магазин",
        description: "Everyone",
        date: "2026-08-13T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55пii5cu47",
        name: "Сделать презентацию",
        description: "Everyone",
        date: "2026-08-24T16:00:00",
        completed: false,
        visibility: "public",
    },
    {
        id: "yiр55ii5u57",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yi55пii5cu67",
        name: "Погулять с собакой",
        description: "Everyone",
        date: "2026-08-24T16:00:00",
        completed: false,
        visibility: "public",
    },
    {
        id: "yiр55ii5u570",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiр55ii5u5709",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiр55ii5u5708",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiр55ii5u5707",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiр55ii5u5706",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiр55ii5u5705",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiр55ii5u5704",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },
    {
        id: "yiр55ii5u5701",
        name: "Покормить кота",
        description: "Everyone",
        date: "2026-08-23T16:00:00",
        completed: false,
        visibility: "private",
    },


]